# Generated by Django 5.2.6 on 2025-10-01 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contareceber',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contareceber',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='valor_pago',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='financeiro.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.contareceber', verbose_name='Conta'),
        ),
    ]
