# Generated by Django 5.2.6 on 2025-10-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_remove_contareceber_status_remove_contareceber_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcela',
            options={'ordering': ['conta__id', 'numero_parcela'], 'verbose_name': 'Parcela', 'verbose_name_plural': 'Parcelas'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
